#!/usr/bin/env python
# Copyright 2024-2025 The PySCF Developers. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import itertools
import ctypes
from dataclasses import dataclass
import numpy as np
import cupy as cp
from pyscf import lib
from pyscf.gto import ATOM_OF, ANG_OF, NPRIM_OF, NCTR_OF, PTR_EXP, PTR_COEFF, PTR_COORD
from pyscf.pbc.df.df_jk import _format_kpts_band
from pyscf.pbc.lib.kpts_helper import is_zero
from gpu4pyscf.lib import logger
from gpu4pyscf.lib import utils
from gpu4pyscf.lib.cupy_helper import contract, transpose_sum
from gpu4pyscf.dft import numint
from gpu4pyscf.pbc import tools
from gpu4pyscf.pbc.df.fft_jk import _format_dms, _format_jks
from gpu4pyscf.pbc.df import ft_ao
from gpu4pyscf.pbc.gto.cell import get_Gv_weights
from gpu4pyscf.gto.mole import SortedGTO
from gpu4pyscf.pbc.df.ft_ao import libpbc


def _get_lattice_Ls_base(cell, rcut=None):
    '''Get the (Cartesian, unitful) lattice translation vectors for nearby images.
    The translation vectors can be used for the lattice summation.

    Kwargs:
        discard:
            Drop less important Ls based on AO values on grid
    '''
    if dimension is None:
        # For atoms near the boundary of the cell, it is necessary (even in low-
        # dimensional systems) to include lattice translations in all 3 dimensions.
        if cell.dimension < 2 or cell.low_dim_ft_type == 'inf_vacuum':
            dimension = cell.dimension
        else:
            dimension = 3
    if rcut is None:
        rcut = cell.rcut

    if dimension == 0 or rcut <= 0 or cell.natm == 0:
        return np.zeros((1, 3))

    a = cell.lattice_vectors()

    scaled_atom_coords = cell.get_scaled_atom_coords()
    atom_boundary_max = scaled_atom_coords[:,:dimension].max(axis=0)
    atom_boundary_min = scaled_atom_coords[:,:dimension].min(axis=0)
    ovlp_penalty = atom_boundary_max - atom_boundary_min
    dR = ovlp_penalty.dot(a[:dimension])
    dR_basis = np.diag(dR)

    # Search the minimal x,y,z requiring |x*a[0]+y*a[1]+z*a[2]+dR|^2 > rcut^2
    # Ls boundary should be derived by decomposing (a, Rij) for each atom-pair.
    # For reasons unclear, the so-obtained Ls boundary seems not large enough.
    # The upper-bound of the Ls boundary is generated by find_boundary function.
    def find_boundary(a):
        aR = np.vstack([a, dR_basis])
        r = np.linalg.qr(aR.T)[1]
        ub = (rcut + abs(r[2,3:]).sum()) / abs(r[2,2])
        return ub

    xb = find_boundary(a[[1,2,0]])
    if dimension > 1:
        yb = find_boundary(a[[2,0,1]])
    else:
        yb = 0
    if dimension > 2:
        zb = find_boundary(a)
    else:
        zb = 0
    bounds = np.ceil([xb, yb, zb]).astype(int)

    Ts = np.hstack((np.arange(-bounds[0], bounds[0]+1),
                    np.arange(-bounds[1], bounds[1]+1),
                    np.arange(-bounds[2], bounds[2]+1)))

if __name__ == '__main__':
    import pyscf
    cell = pyscf.M(
        atom='C1 0 0 0; C2 .2 .3 .7',
        basis=[[0, [3, 1]], [1, [1, 1]], [1, [.8, 1]]],
        a=np.eye(3) * 3.2,
        mesh=[1,3,3]
    )

    cp.random.seed(4)
    nao = cell.nao
    dm = cp.random.rand(nao, nao)
    dm = dm + dm.T

    Gv, Gvbase, w = get_Gv_weights(cell)

    Gpq = ft_ao.ft_aopair(cell, Gv)
    rho_ref = cp.einsum('pq,Gpq->G', dm, Gpq)
    vj_ref = cp.einsum('G,Gpq->pq', rho_ref, Gpq)
    print('----------')

    cell = SortedGTO.from_cell(cell)
    mesh = np.asarray(cell.mesh, dtype=np.int32)

    ftopt = ft_ao.FTOpt(cell).build()
    envs = cell.rys_envs
    bas_ij_idx, shl_pair_offsets = cell.aggregate_shl_pairs(ftopt.bas_ij_cache, 32)
    bas_ij_idx = cp.asarray(bas_ij_idx, dtype=np.uint32)
    shl_pair_offsets = cp.asarray(shl_pair_offsets, dtype=np.int32)
    nbatches_shl_pair = len(shl_pair_offsets) - 1

    b = cell.reciprocal_vectors()
    G_bases = cp.array(np.hstack([Gvbase[0] * b[0,0],
                                  Gvbase[1] * b[1,1],
                                  Gvbase[2] * b[2,2]]))

    nimgs = (np.array(cell.nimgs)*2+1)
    a = cell.lattice_vectors()
    Tx = (np.arange(nimgs[0]) - nimgs[0]//2) * a[0,0]
    Ty = (np.arange(nimgs[1]) - nimgs[1]//2) * a[1,1]
    Tz = (np.arange(nimgs[2]) - nimgs[2]//2) * a[2,2]
    L_bases = cp.array(np.hstack([Tx, Ty, Tz]))
    mesh_cum = cp.array(np.append(0, np.cumsum(mesh)), dtype=np.int32)
    nimgs_cum = cp.array(np.append(0, np.cumsum(nimgs)), dtype=np.int32)

    dm = cell.apply_C_mat_CT(dm)
    transpose_sum(dm)

    rhoR = cp.zeros(mesh)
    rhoI = cp.zeros(mesh)
    libpbc.contract_orth_aopair_dm(
        ctypes.cast(rhoR.data.ptr, ctypes.c_void_p),
        ctypes.cast(rhoI.data.ptr, ctypes.c_void_p),
        ctypes.cast(dm.data.ptr, ctypes.c_void_p),
        ctypes.byref(envs),
        ctypes.cast(shl_pair_offsets.data.ptr, ctypes.c_void_p),
        ctypes.cast(bas_ij_idx.data.ptr, ctypes.c_void_p),
        ctypes.cast(G_bases.data.ptr, ctypes.c_void_p),
        ctypes.cast(L_bases.data.ptr, ctypes.c_void_p),
        ctypes.cast(mesh_cum.data.ptr, ctypes.c_void_p),
        ctypes.cast(nimgs_cum.data.ptr, ctypes.c_void_p),
        mesh.ctypes, ctypes.c_int(nbatches_shl_pair))
    print(abs(rho_ref.real - rhoR.ravel()).max())
    print(abs(rho_ref.imag - rhoI.ravel()).max())

    vj = cp.zeros_like(dm)
    libpbc.contract_orth_aopair_coulG(
        ctypes.cast(vj.data.ptr, ctypes.c_void_p),
        ctypes.cast(rhoR.data.ptr, ctypes.c_void_p),
        ctypes.cast(rhoI.data.ptr, ctypes.c_void_p),
        ctypes.byref(envs),
        ctypes.cast(bas_ij_idx.data.ptr, ctypes.c_void_p),
        ctypes.cast(G_bases.data.ptr, ctypes.c_void_p),
        ctypes.cast(L_bases.data.ptr, ctypes.c_void_p),
        ctypes.cast(mesh_cum.data.ptr, ctypes.c_void_p),
        ctypes.cast(nimgs_cum.data.ptr, ctypes.c_void_p),
        mesh.ctypes, ctypes.c_int(len(bas_ij_idx)))
    transpose_sum(vj)
    vj = cell.apply_CT_mat_C(vj)
    print(abs(vj_ref.real - vj).max())
