name: Unittest dev

on:
  workflow_dispatch:

jobs:
  manual-single-gpu:
    runs-on: [self-hosted, Linux, X64, v100]
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v3

    - name: Pull CUDA Devel Image
      run: |
        docker pull pyscf/gpu4pyscf-devel:pyscf-2.8

    - name: Test with pytest
      run: |
        docker run --gpus all \
          --rm \
          -e CUPY_CACHE_DIR=/workspace/.cupy_cache \
          -e HTTP_PROXY=$HTTP_PROXY \
          -e HTTPS_PROXY=$HTTPS_PROXY \
          -v $GITHUB_WORKSPACE:/workspace \
          -v ~/.cache/pip:/root/.cache/pip \
          pyscf/gpu4pyscf-devel:pyscf-2.8 \
          /bin/bash -c "cd /workspace && pip3 install --no-cache-dir --target=/tmp/deps -r requirements.txt && export PYTHONPATH=/tmp/deps:$PYTHONPATH && source build.sh && pytest -m 'not slow and not benchmark' --cov=/workspace --durations=50 && rm -rf .pytest_cache"
